PreCommit:
  BundleCheck:
    enabled: true

  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop']
    on_warn: fail
    include:
      - '**/*.gemspec'
      - '**/*.rb'
      - '**/Gemfile'
    problem_on_unmodified_line: ignore

  TrailingWhitespace:
    enabled: true

  YamlSyntax:
    enabled: true
